export interface Aluno {
  id?: string,
  nome: string,
  email: string,
  senha: string,
  matricula: string,
  dataNascimento: string,
  genero: string,
  cpf: string,
  endereco: string,
  telefone: string,
  rg: string,
  foto: string,
  turmaId: string,
}
